version: '3.8'
services:
  angular_app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: angular_app_prod
    ports:
      - 8080:80

# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml down -v
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build